package com.websystique.springmvc.model;
// Generated Sep 19, 2017 2:55:09 PM by Hibernate Tools 4.3.1



/**
 * Contador generated by hbm2java
 */
public class Contador  implements java.io.Serializable {


     private Integer id;
     private Integer numero;

    public Contador() {
    }

    public Contador(Integer numero) {
       this.numero = numero;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }




}


