package com.websystique.springmvc.model;
// Generated Sep 19, 2017 2:55:09 PM by Hibernate Tools 4.3.1



/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private Integer id;
     private String departamento;
     private String prefijo;

    public Departamentos() {
    }

    public Departamentos(String departamento, String prefijo) {
       this.prefijo=prefijo; 
       this.departamento = departamento;
    }
    
     public Departamentos(int id, String departamento, String prefijo) {
       this.id = id;  
       this.prefijo=prefijo; 
       this.departamento = departamento;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    public String getPrefijo() {
        return prefijo;
    }

    public void setPrefijo(String prefijo) {
        this.prefijo = prefijo;
    }
    
    



}


