package com.websystique.springmvc.model;
// Generated Sep 19, 2017 2:55:09 PM by Hibernate Tools 4.3.1



/**
 * Estaciones generated by hbm2java
 */
public class Estaciones  implements java.io.Serializable {


     private Integer id;
     private String departamento;
     private Integer usuarioFk;
     private String estatus;
     private String estacion;

    public Estaciones() {
    }

    public Estaciones(String estacion, String departamento) {
       this.estacion = estacion;
       this.departamento = departamento;
    }
    
     public Estaciones(int id, String estacion, String departamento) {
         this.id = id;
       this.estacion = estacion;
       this.departamento = departamento;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEstacion() {
        return this.estacion;
    }
    
    public void setEstacion(String estacion) {
        this.estacion = estacion;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    public Integer getUsuarioFk() {
        return usuarioFk;
    }

    public void setUsuarioFk(Integer usuarioFk) {
        this.usuarioFk = usuarioFk;
    }

    public String getEstatus() {
        return estatus;
    }

    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }

    
    


}


