package com.websystique.springmvc.model;
// Generated Sep 19, 2017 2:55:09 PM by Hibernate Tools 4.3.1



/**
 * Servicios generated by hbm2java
 */
public class Servicios  implements java.io.Serializable {


     private Integer id;
     private String tipoServicio;
     private String departamento;

    public Servicios() {
    }

    public Servicios(String tipoServicio, String departamento) {
       this.tipoServicio = tipoServicio;
       this.departamento = departamento;
    }
    
    public Servicios(int id,String tipoServicio, String departamento) {
       this.id = id;
       this.tipoServicio = tipoServicio;
       this.departamento = departamento;
    }
   
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTipoServicio() {
        return this.tipoServicio;
    }
    
    public void setTipoServicio(String tipoServicio) {
        this.tipoServicio = tipoServicio;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }




}


