package com.websystique.springmvc.model;
// Generated Sep 19, 2017 2:55:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tickets generated by hbm2java
 */
public class Tickets  implements java.io.Serializable {


     private Integer id;
     private String turno;
     private String servicio;
     private String nombreCliente;
     private String apellidoCliente;
     private String cedulaCliente;
     private String status;
     private Date fechaHora;
     private Date fechaCierre;
     private Integer usuariofk;
     private String departamento;

    public Tickets() {
    }

    public Tickets(String turno, String servicio, String nombreCliente, String apellidoCliente, String cedulaCliente, String status, Date fechaHora, Date fechaCierre, Integer usuariofk, String departamento) {
       this.turno = turno;
       this.servicio = servicio;
       this.nombreCliente = nombreCliente;
       this.apellidoCliente = apellidoCliente;
       this.cedulaCliente = cedulaCliente;
       this.status = status;
       this.fechaHora = fechaHora;
       this.fechaCierre = fechaCierre;
       this.usuariofk = usuariofk;
       this.departamento = departamento;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTurno() {
        return this.turno;
    }
    
    public void setTurno(String turno) {
        this.turno = turno;
    }
    public String getServicio() {
        return this.servicio;
    }
    
    public void setServicio(String servicio) {
        this.servicio = servicio;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getApellidoCliente() {
        return this.apellidoCliente;
    }
    
    public void setApellidoCliente(String apellidoCliente) {
        this.apellidoCliente = apellidoCliente;
    }
    public String getCedulaCliente() {
        return this.cedulaCliente;
    }
    
    public void setCedulaCliente(String cedulaCliente) {
        this.cedulaCliente = cedulaCliente;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Date getFechaCierre() {
        return this.fechaCierre;
    }
    
    public void setFechaCierre(Date fechaCierre) {
        this.fechaCierre = fechaCierre;
    }
    public Integer getUsuariofk() {
        return this.usuariofk;
    }
    
    public void setUsuariofk(Integer usuariofk) {
        this.usuariofk = usuariofk;
    }

    public String getDepartamento() {
        return departamento;
    }

    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }


    

}


