package com.websystique.springmvc.model;
// Generated Sep 19, 2017 2:55:09 PM by Hibernate Tools 4.3.1



/**
 * Turnos generated by hbm2java
 */
public class Turnos  implements java.io.Serializable {


     private Integer id;
     private String turno;
     private String estacion;
     private Integer usuarioFk;
     private String duracion;
     private String status;
     private String servicio;
     private Integer ticketFk;

    public Turnos() {
    }

    public Turnos(String turno, String estacion, Integer usuarioFk, String duracion, String status, String servicio, Integer ticketFk) {
       this.turno = turno;
       this.estacion = estacion;
       this.usuarioFk = usuarioFk;
       this.duracion = duracion;
       this.status = status;
       this.servicio = servicio;
       this.ticketFk = ticketFk;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTurno() {
        return this.turno;
    }
    
    public void setTurno(String turno) {
        this.turno = turno;
    }

    public Integer getUsuarioFk() {
        return this.usuarioFk;
    }
    
    public void setUsuarioFk(Integer usuarioFk) {
        this.usuarioFk = usuarioFk;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getServicio() {
        return this.servicio;
    }
    
    public void setServicio(String servicio) {
        this.servicio = servicio;
    }
    public Integer getTicketFk() {
        return this.ticketFk;
    }
    
    public void setTicketFk(Integer ticketFk) {
        this.ticketFk = ticketFk;
    }

    public String getEstacion() {
        return estacion;
    }

    public void setEstacion(String estacion) {
        this.estacion = estacion;
    }

    
    


}


